version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    networks:
      - backend_network
    volumes:
      - data:/var/lib/postgresql/data

  crud-nestjs:
    container_name: crud-nestjs
    build:
      context: ./
      dockerfile: Dockerfile
    image: crud-nestjs
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
    networks:
      - backend_network
    depends_on:
      - postgres

volumes:
  data:

networks:
  backend_network:
    driver: bridge
